---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: kube-system
spec:
  ports:
  - name: phpmyadmin
    port: 80
  clusterIP: None
  selector:
    app: phpmyadmin
